# Day-5: 데이터 분석1

# Pandas-1

- 판다스는 파이썬에서 사용하는 데이터 분석 라이브러리이다.
- Pandas는 Series와 DataFrame이라는 자료구조를 제공한다.

## Series

- 시리즈는 1차원 배열에 인덱스를 가지고 있는 구조이다.

- 이때 값은 인덱스 번호로도 접근 할 수 있고 인덱스명으로도 접근할 수 있다.

- 즉, 인덱스 번호로 값을 접근할 수 있는 리스트(list)와 인덱스명과 같은 키(key)로 값을 접근할 수 있는 딕셔너리(dict)의 장점을 섞어 놓은 자료구조이다.

### 시리즈 생성
- 시리즈를 생성하기 위해서는 먼저 pandas 모듈을 불러와야 한다.
- pandas 모듈은 보통 pd라는 별칭을 사용한다.

In [2]:
import pandas as pd

```python
pd.Series(list or dict or array, index = list or array)
```

In [ ]:
score = [84, 21, 87, 100, 59, 46]

- index 옵션을 통해 인덱스명을 설정할 수 있다.

In [ ]:
score = [84, 21, 87, 100, 59, 46]
names=['철수','영이','길동','미영','순이','철이']

철수     84
영이     21
길동     87
미영    100
순이     59
철이     46
dtype: int64

- 딕셔너리를 넣어서 시리즈를 생성할 수 있다.

In [ ]:
dic={'철수':84, '영이':21, '길동':87,'미영':100, '순이':59, '철이':46}

철수     84
영이     21
길동     87
미영    100
순이     59
철이     46
dtype: int64

### 시리즈 산술연산
- 시리즈에 산술연산을 적용해보자. 이때, 연산하여 나온 결과 또한 시리즈타입이다.

In [ ]:
import pandas as pd
names1=['철수','영이','길동','미영','순이','철이']
score1 = [84, 21, 87, 100, 59, 46]
names2 =['길동','철수','영이','철이','순이','미영']
score2 = [99, 87, 87, 84, 77, 15]

철수     84
영이     21
길동     87
미영    100
순이     59
철이     46
dtype: int64
길동    99
철수    87
영이    87
철이    84
순이    77
미영    15
dtype: int64

### 시리즈 인덱싱
- 시리즈의 데이터에 접근은 인덱스 번호 또는 인덱스명를 통해 가능하다.

### 시리즈 슬라이싱
```
시리즈변수명[start:end:step]
```

### 시리즈 데이터 추가, 수정, 삭제

```
시리즈명[인덱스] = value
```

- '슬기' 점수 87를 추가해보자.

철수     84
영이     21
길동     87
미영    100
순이     59
철이     46
슬기     87
dtype: int64

- '길동' 점수를 88점으로 수정해보자.

철수     84
영이     21
길동     88
미영    100
순이     59
철이     46
슬기     87
dtype: int64

- 시리즈에서 데이터 삭제는 키워드 del을 통해 가능하다.
- '철이'를 삭제해보자.

- .drop()을 옵션 inplace없이 사용했을 때는 원본 데이터에는 변동이 없다.

### 시리즈 비교연산과 필터링

- 시리즈에서도 비교연산의 결과를 필터링하는데 사용할 수 있다.
- 아래 코드는 시리즈 s1에서 85이상인 값들에 대해서 필터링한다.

## DataFrame

DataFrame은 행과 열로 이루어진 2차원 형태의 배열이다.
이때 한 개의 열(칼럼)은 하나의 시리즈이며, DataFrame은 시리즈들의 묶음이다.

### 데이타프레임 생성

- 데이타프레임 생성 형식은 다음과 같다.
```
pd.DataFrame(list or array or series or dictionary, index = list or array, columns = list or array)
```

- 먼저, 시리즈를 이용하여 데이터프레임을 생성해보자.
- 아래와 같이 시리즈 2개를 만들자.

In [ ]:
names1=['철수','영이','길동','미영','순이','철이']
score1 = [84, 21, 87, 100, 59, 46]
names2 =['길동','철수','영이','철이','순이','미영']
score2 = [99, 87, 87, 84, 77, 15]

s1 = pd.Series(score1, index=names1)
s2 = pd.Series(score2, index=names2)
print(s1)
print(s2)

- 시리즈를 데이타프레임의 열(column)로 넣어준다.

     국어  영어   합계
철수   84  87  171
영이   21  87  108
길동   87  99  186
미영  100  15  115
순이   59  77  136
철이   46  84  130

- 데이타프레임을 리스트나 어레이로도 만들 수 있다.

In [ ]:
scores = [[84,87,78], [21,15,84], [87,84,76], [100,87,99],[59,99,59],[46,77,56]]
#todo

     0   1   2
0   84  87  78
1   21  15  84
2   87  84  76
3  100  87  99
4   59  99  59
5   46  77  56

- 데이터프레임에 옵션 index와 columns에 인덱스와 칼럼명을 직접 명시해줄 수도 있다.

In [ ]:
scores = [[84,87,78], [21,15,84], [87,84,76], [100,87,99],[59,99,59],[46,77,56]]
names=['철수','영이','길동','미영','순이','철이']
lectures=['국어','수학','영어']
#todo

     국어  수학  영어
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

- 딕셔너리를 데이터로 넣어 줄 수도 있다.

In [ ]:
ScoresWithLectures={'국어':[84,21,87,100,59,46], '수학':[87,15,84,87,99,77], '영어':[78,84,76,99,59,56]}
names=['철수','영이','길동','미영','순이','철이']

     국어  수학  영어
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

### 파일 입출력

|파일 형식|읽기|쓰기|
|:----------:|:----------|:----------|
|MS Excel|read_excel| to_excel|
|CSV|read_csv| to_csv|
|JSON|read_json|to_json|
|HTML|read_html|to_html|
|Local clipboard|read_clipboard|to_clipboard|
|HDF5 format|read_hdf|to_hdf|
|SQL|read_sql|to_sql|

- csv 파일을 불러올 때
  - pd.read_csv('파일명', index_col=칼럼번호, encoding='인코딩방법')
    - index_col:칼럼번호를 설정인덱스로 지정한다.
    - usecols: 사용할 칼럼번호를 지정한다.
    - header: 헤더(칼럼)으로 선택할 헤더를 지정한다.
    - encoding: 한글이 깨질때에는 encoding 옵션에 'euc-kr'을 넣어준다.
    - 이 외에도 많은 옵션이 있다.

- excel파일을 불러올 때
  - pd.read_excel('파일명', encoding='인코딩방법')

In [ ]:
# 엑셀로 저장하기

In [ ]:
# 엑셀 읽어오기

- index_col 옵션은 인덱스 칼럼을 지정하여 읽어올 수 있게 해준다.

In [ ]:
# csv로 저장하기

### 데이터프레임 확인
- 데이터프레임의 정보를 확인하기 위해 다음과 같은 변수 또는 메서드를 사용한다.
  - .shape: 모양을 확인한다.
  - .columns: 열이름을 확인한다.
  - head(): 데이터프레임의 맨 위 5개 행을 보여준다.
  - tail(): 데이터프레임의 맨 아래 5개 행을 보여준다.
  - info(): 칼럼명, Non-Null count, Dtype 정보를 보여준다.
  - isnull().sum(): 값이 없는(null) 갯수를 반환한다.

```
url='https://raw.githubusercontent.com/HaesunByun/Basic-Computing/main/titanic_test.csv'
titanic_test = pd.read_csv(url)
titanic_test
```
- passenger ID
- Pclass: 티켓 클래스. (1 = 1st, 2 = 2nd, 3 = 3rd)
- Name: 이름
- Sex: 성별
- Age: 나이(세)
- Sibsp (Siblings and spouse): 함께 탑승한 형제자매, 배우자 수 총합
- Parch (Parents and children): 함께 탑승한 부모, 자녀 수 총합
- Ticket: 티켓 번호
- Fare: 탑승 요금
- Cabin: 객실 번호
- Embarked: 탑승 항구

In [ ]:
url='https://raw.githubusercontent.com/HaesunByun/Basic-Computing/main/titanic_test.csv'
titanic_test = pd.read_csv(url)
titanic_test

In [ ]:
titanic_test.shape
titanic_test.columns
titanic_test.head(3)
titanic_test.tail()
titanic_test.info()
titanic_test.isnull().sum()

### 인덱스/칼럼명 변경
- .index를 이용하여 리스트 또는 배열로 인덱스를 넣어줘서 인덱스를 변경 또는 생성할 수 있다.

In [ ]:
d3

     국어  수학  영어
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

In [ ]:
d3.index = ['학생1','학생2','학생3','학생4','학생5','학생6']
d3

      국어  수학  영어
학생1   84  87  78
학생2   21  15  84
학생3   87  84  76
학생4  100  87  99
학생5   59  99  59
학생6   46  77  56

- 인덱스의 일부만 변경하고자 할때에는
.rename(index={기존 index : 새 index, ...}, [inplace=True])을 사용한다.

In [ ]:
d3.rename(index={'학생1':'철수'}, inplace=True)
d3

      국어  수학  영어
철수    84  87  78
학생2   21  15  84
학생3   87  84  76
학생4  100  87  99
학생5   59  99  59
학생6   46  77  56

- .columns를 이용하여 리스트 또는 배열로 칼럼명를 넣어줘서 칼럼명을 변경 또는 생성할 수 있다.

In [ ]:
d3.columns = ['과목1', '과목2', '과목3']
d3

     과목1  과목2  과목3
철수    84   87   78
학생2   21   15   84
학생3   87   84   76
학생4  100   87   99
학생5   59   99   59
학생6   46   77   56

- 칼럼명의 일부만 변경하고자 할때에는
.rename(columns={기존 칼럼명 : 새 칼럼명, ...}, [inplace=True])을 사용한다.

In [ ]:
d3.rename(columns={'과목1':'국어'}, inplace=True)
d3

      국어  과목2  과목3
철수    84   87   78
학생2   21   15   84
학생3   87   84   76
학생4  100   87   99
학생5   59   99   59
학생6   46   77   56

### 열순서 변경

- 열순서를 변경하기 위해 인덱스와 칼럼명을 원래대로 다시 되돌려보자.

In [ ]:
d3.index = ['철수','영이','길동','미영','순이','철이']
d3.columns = ['국어','수학','영어']
d3

     국어  수학  영어
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

- 변경하고자 하는 순서대로 리스트로 만들어 넣어주면 순서를 변경할 수 있다.

In [ ]:
a = ['국어','영어','수학']
d4=d3[['국어','영어','수학']]
#d3[['국어', '수학']]
d3

     국어  수학  영어
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

- 오름차순 또는 내림차순(reverse=True)으로 순서를 만들어주고자 할때에는 sorted()함수를 이용하면 된다.

In [ ]:
a = sorted(d3.index)
a

['길동', '미영', '순이', '영이', '철수', '철이']

In [ ]:
d3.columns

Index(['국어', '수학', '영어'], dtype='object')

In [ ]:
#a = sorted(d3.columns)
d3[a]

KeyError: "None of [Index(['길동', '미영', '순이', '영이', '철수', '철이'], dtype='object')] are in the [columns]"

### 데이터프레임 인덱싱과 슬라이싱

#### 데이터프레임명.iloc[]

- iloc는 index location의 약자로 위치 인덱스로만 인덱싱과 슬라이싱을 할 수 있다.
- .iloc[]을 사용하여 행추출/열추출/행렬추출을 해보자.
- 형식은 다음과 같다.
```
데이터프레임명.iloc[행 또는 행범위, 열 또는 열범위]
```
- 이때 행이든 열이든 범위가 아닌 하나만 명시했다면 그 결과는 시리즈로 나온다.
- 행과 열 모두 범위로 명시했다면 그 결과는 데이터프레임으로 나온다.

- 행추출
  - 열은 생략할 수 있다.

- 열추출
  - 행은 생략할 수 없다.

- 행열 추출

#### 데이터프레임명.loc[]
- 설정 인덱스로만 인덱싱과 슬라이싱을 할 수 있다.
- 사용하는 방법은 다음과 같다.

```
데이터프레임명.loc[행 또는 행범위, 열 또는 열범위]
```
- 이때 행이든 열이든 범위가 아닌 하나만 명시했다면 그 결과는 시리즈로 나온다.
- 행과 열 모두 범위로 명시했다면 그 결과는 데이터프레임으로 나온다.

- 행추출
  - 열은 생략할 수 있다.

- 열추출
  - 행은 생략할 수 없다.

- 행렬추출

#### 데이터프레임명
- 데이터프레임명만 사용하여 추출하는 방법이 조금 복잡하다.

- 행추출은 하나의 행을 추출하더라도 반드시 **슬라이싱**으로 해야 한다. 그렇지 않으면 열이름으로 인식해 에러가 난다.
```
데이터프레임명[행범위]
```

In [ ]:
#d3['길동':'철이']

- 열추출은 반드시 **칼럼명으로만** 추출가능하다.
- 여러 칼럼을 추출할 때에는 **리스트**로 넣어준다.
```
데이터프레임명[열이름 또는 열이름 리스트]
```

- 행렬추출은 **행렬의 대괄호 순서를 바꿀 수 있지만** 행추출, 열추출 제약사항이 그대로 적용된다.
  - 행추출은 **슬라이싱으로만!**
  - 열추출은 **칼럼명으로만!**
  - 여러 열을 추출할 때에는 **리스트로만!**
```
데이터프레임명[행범위][열이름 또는 열이름 리스트]
데이터프레임명[열이름 또는 열이름 리스트][행범위]
```

In [ ]:
d3['길동':'미영'][['국어','수학']]
d3[['국어','수학']]['길동':'미영']

     국어  수학
길동   87  84
미영  100  87

### 데이터프레임 행/열 추가, 수정, 삭제

- '컴기' 열을 추가해보자.
- '컴기'라는 칼럼이 없으면 추가되고, 있으면 수정이 된다.

In [ ]:
comScore=[60, 70, 56, 74, 77, 66]

     국어  수학  영어  컴기
철수   84  87  78  60
영이   21  15  84  70
길동   87  84  76  56
미영  100  87  99  74
순이   59  99  59  77
철이   46  77  56  66

- '나리' 행을 추가해보자.
- .loc[인덱스명]을 통해 추가할 수 있으며, '나리'행이 있으면 수정된다.

In [ ]:
nari_score = [80, 90, 87, 76]

     국어  수학  영어  컴기
철수   84  87  78  60
영이   21  15  84  70
길동   87  84  76  56
미영  100  87  99  74
순이   59  99  59  77
철이   46  77  56  66
나리   80  90  87  76

- '컴기'열을 삭제해보자.

     국어  수학  영어
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56
나리   80  90  87

- '나리'행을 삭제해보자.

     국어  수학  영어
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

### 산술/비교연산 및 필터링
- 배열, 시리즈에서의 연산과 비슷하다.
- 수학과 영어 성적을 더해보자.

- 수학이 60점 이상인 학생들을 나열해보자.

수학이 60점 이상인 학생들의 수학점수만 나열해보자.

### 정렬하기
- sort_index()를 통해 인덱스를 기준으로 정렬한다.

- 특정 칼럼명을 기준으로 정렬한다.

## 통계함수 적용하기

- mean(): 평균값

- median(): 주어진 값들을 크기 순서대로 정렬했을 때 가장 중앙에 위치하는 값
- 값이 짝수일때는 중앙에 있는 두 값의 평균을 나타낸다.

77.0

- max(): 최댓값
- min(): 최솟값

- var():분산, 관측값에서 평균을 뺀 값을 제곱하고, 그것을 모두 더한 후 전체 개수로 나눠서 구한다.
- std():표준편차, 분산을 제곱근한 것

- corr(): 상관계수, 두 변수간의 관계강도를 나타냄

## Problem: 조건에 맞는 데이터 찾아보기

- 아래 데이터로 데이터프레임을 만든 후 조건에 맞는 데이터를 찾아보세요.

```
김철수	남	60	전문직
김미영	여	62	기타
이수지	여	20	학생
홍길동	남	32	직장인
이철	남	45	자영업
```

In [ ]:
import pandas as pd

# 데이터 생성


# 데이터프레임 생성

    이름 성별  나이   직업
0  김철수  남  60  전문직
1  김미영  여  62   기타
2  이수지  여  20   학생
3  홍길동  남  32  직장인
4   이철  남  45  자영업

### 여성고객 추출하기

### 나이가 60 이상인 여성 고객 명단 추출하기

In [ ]:
# 나이가 60 이상이고 성별이 '여'인 고객 명단 추출

    이름 성별  나이  직업
1  김미영  여  62  기타

### 30, 40대 고객 명단 추출하기

In [ ]:
# 30, 40대 고객 명단 추출

    이름 성별  나이   직업
3  홍길동  남  32  직장인
4   이철  남  45  자영업

### 나이가 많은 사람부터 적은 사람 순서로 정렬하기

In [ ]:
# 나이가 많은 사람부터 적은 사람 순서로 정렬

    이름 성별  나이   직업
1  김미영  여  62   기타
0  김철수  남  60  전문직
4   이철  남  45  자영업
3  홍길동  남  32  직장인
2  이수지  여  20   학생

### 이름 순서로 정렬하기

In [ ]:
# 이름 순서로 정렬

    이름 성별  나이   직업
1  김미영  여  62   기타
0  김철수  남  60  전문직
2  이수지  여  20   학생
4   이철  남  45  자영업
3  홍길동  남  32  직장인

## Problem: 월별 교통사고 사상자수 구하기
😄 주어진 링크를 통해 아래와 같은 데이터프레임을 가져와 주세요.<br>

url: https://raw.githubusercontent.com/HaesunByun/common/main/data/drowsydriving.csv

```
  구분   승용차 사고 사망 부상
201401 16561665  169   7   347
201402 16626372  145   3   268
201403 16691079  206  12   358
             ...
 ```

😄 '사상자수'를 나타내는 칼럼을 새롭게 추가하세요.
'사상자수'는 아래와 같은 공식을 통해 계산됩니다.
```
사상자수 = 사망(명) + 부상(명)
 ```

output sample
```
  구분   승용차 사고 사망 부상 사상자수
201402 16626372  145   3   268     271
201602 18179420  174   6   328     334
201412 17273442  178  12   329     341
            ...
 ```

😄 '사상자수'의 최댓값&최솟값을 출력하고 사상자수를 기준으로 오름차순 정렬한 결과를 5개의 행만 출력해보세요.

output sample
```
최대 사상자수: 563명
최소 사상자수: 271명
```

## Problem: 월별 교통사고 위험지수 구하기
😄 월별 '위험지수'을 나타내는 칼럼을 새롭게 추가해주세요.

'위험지수'은 아래와 같은 공식을 통해 계산됩니다.
```
위험지수 = 10000 * ( 사고(건) + 20 * 사망(명) + 2 * 부상(명) ) / 승용차(대)
 ```
그리고 위험지수의 최댓값과 최솟값을 출력하고,
데이터프레임을 '위험지수' 칼럼을 기준으로 내림차순 정렬하세요.

output sample
```
최대 위험지수: 0.9645
최소 위험지수: 0.4457

  구분   승용차 사고 사망 부상 사상자수  위험지수
201508 17791145  268  19   534     553   0.964525
201405 16820493  218  17   474     491   0.895336
201507 17726433  273   7   556     563   0.860297
            ...
 ```