# Day-7: Chat-GPT를 활용한 데이터 분석

# I. Pandas-2

In [ ]:
import pandas as pd
ScoresWithLectures={'국어':[84,21,87,100,59,46], '수학':[87,15,84,87,99,77], '영어':[78,84,76,99,59,56]}
names=['철수','영이','길동','미영','순이','철이']
#todo 변수 df에 데이터프레임을 생성해주세요.

### 데이터프레임 인덱싱과 슬라이싱

#### 데이터프레임명.iloc[]

- iloc는 index location의 약자로 위치 인덱스로만 인덱싱과 슬라이싱을 할 수 있다.
- .iloc[]을 사용하여 행추출/열추출/행렬추출을 해보자.
- 형식은 다음과 같다.
```
데이터프레임명.iloc[행 또는 행범위, 열 또는 열범위]
```
- 이때 행이든 열이든 범위가 아닌 하나만 명시했다면 그 결과는 시리즈로 나온다.
- 행과 열 모두 범위로 명시했다면 그 결과는 데이터프레임으로 나온다.

- 행추출
  - 열은 생략할 수 있다.

- 열추출
  - 행은 생략할 수 없다.

- 행열 추출

#### 데이터프레임명.loc[]
- 설정 인덱스로만 인덱싱과 슬라이싱을 할 수 있다.
- 사용하는 방법은 다음과 같다.

```
데이터프레임명.loc[행 또는 행범위, 열 또는 열범위]
```
- 이때 행이든 열이든 범위가 아닌 하나만 명시했다면 그 결과는 시리즈로 나온다.
- 행과 열 모두 범위로 명시했다면 그 결과는 데이터프레임으로 나온다.

- 행추출
  - 열은 생략할 수 있다.

- 열추출
  - 행은 생략할 수 없다.

- 행렬추출

#### 데이터프레임명
- 데이터프레임명만 사용하여 추출하는 방법이 조금 복잡하다.

- 행렬추출은 **행렬의 대괄호 순서를 바꿀 수 있지만** 행추출, 열추출 제약사항이 그대로 적용된다.
  - 행추출은 **슬라이싱으로만!**
  - 열추출은 **칼럼명으로만!**
  - 여러 열을 추출할 때에는 **리스트로만!**
```
데이터프레임명[행범위][열이름 또는 열이름 리스트]
데이터프레임명[열이름 또는 열이름 리스트][행범위]
```

In [ ]:
df[['국어','수학']]['길동':'미영']

### 데이터프레임 행/열 추가, 수정, 삭제

- '컴기' 열을 추가해보자.
- '컴기'라는 칼럼이 없으면 추가되고, 있으면 수정이 된다.

In [ ]:
comScore=[60, 70, 56, 74, 77, 66]

- '나리' 행을 추가해보자.
- .loc[인덱스명]을 통해 추가할 수 있으며, '나리'행이 있으면 수정된다.

In [ ]:
nari_score = [80, 90, 87, 76]

- .drop()으로 '컴기'열을 삭제해보자.

- .drop()으로 '나리'행을 삭제해보자.

### 산술/비교연산 및 필터링
- 배열, 시리즈에서의 연산과 비슷하다.

- 수학과 영어 점수를 더해보자.

- 수학이 60점 이상인 사람들을 찾아보자.

### 정렬하기
- sort_index()를 통해 인덱스를 기준으로 정렬한다. ascending옵션으로 오름차순, 내림차순을 설정할 수 있다.

- sort_values()는 특정 칼럼명을 기준으로 정렬한다.

## 파일 입출력

|파일 형식|읽기|쓰기|
|:----------:|:----------|:----------|
|MS Excel|read_excel| to_excel|
|CSV|read_csv| to_csv|
|JSON|read_json|to_json|
|HTML|read_html|to_html|
|Local clipboard|read_clipboard|to_clipboard|
|HDF5 format|read_hdf|to_hdf|
|SQL|read_sql|to_sql|

- 파일 읽고 저장하기

In [ ]:
import pandas as pd
scores = [[84,87,78], [21,15,84], [87,84,76], [100,87,99],[59,99,59],[46,77,56]]
names=['철수','영이','길동','미영','순이','철이']
lectures=['국어','수학','영어']
d1 = pd.DataFrame(scores, index=names, columns=lectures)
d1

In [ ]:
# 엑셀로 저장하기
d1.to_excel('sample.xlsx', encoding='euc-kr')

In [ ]:
# 엑셀 읽어오기
d2 = pd.read_excel("sample.xlsx")
d2

In [ ]:
d2 = pd.read_excel("sample.xlsx", index_col=0)
d2

In [ ]:
# csv로 저장하기
d2.to_csv('sample.csv', encoding='euc-kr')

## 통계함수 적용하기

- mean(): 평균값

In [ ]:
d1.mean()

- median(): 주어진 값들을 크기 순서대로 정렬했을 때 가장 중앙에 위치하는 값
- 값이 짝수일때는 중앙에 있는 두 값의 평균

In [ ]:
d1['영어'].median()

- max(): 최댓값
- min(): 최솟값

In [ ]:
print(d1['영어'].max())
print(d1['국어'].min())

- var():분산, 관측값에서 평균을 뺀 값을 제곱하고, 그것을 모두 더한 후 전체 개수로 나눠서 구한다.
- std():표준편차, 분산을 제곱근한 것

In [ ]:
print(d1.var())
print(d1.std())

- corr(): 상관계수, 두 변수간의 관계강도를 나타냄

In [ ]:
d1.corr()

## 자료형 다루기
- .astype(자료형)

In [ ]:
d1.astype('str')

## 누락값 처리하기

- 누락 데이터 확인
  - isnull(): 누락 데이터이면 True, 유효한 데이터이면 False를 반환
  - notnull():유효한 데이터이면 True, 누락데이터이면 False를 반환

In [ ]:
scores = [[84,87,78], [21,15,84], [87,84,76], [100,87,99],[59,99,59],[46,77,56]]
names=['철수','영이','길동','슬기','순이','철이']
lectures=['국어','수학','영어']
d2 = pd.DataFrame(scores, index=names, columns=lectures)
d2

In [ ]:
d3=d1+d2
d3

In [ ]:
d3.isnull()
#d3.notnull()

- 누락 데이터 제거
  - 행제거: .dropna(subset=칼럼명, how='any'/'all', axis=0, thresh=개수)
  - 열제거: .dropna(axis=1, thresh=개수)
  - thresh: 유효한 값의 개수가 thresh보다 작은 행이나 열을 삭제

In [ ]:
d3

In [ ]:
d4=d3.dropna(axis=0)
d4

- 누락 데이터 치환
  - .fillna(값)

In [ ]:
min_kor = d3['국어'].min()
d3['국어'].fillna(min_kor, inplace=True)
d3

## 중복데이터 처리

- .duplicated(): 중복 확인

In [ ]:
d3

In [ ]:
d3.duplicated()

In [ ]:
d3['국어'].duplicated()

- 중복행 제거:  .drop_duplicates(subset=컬럼명리스트)

In [ ]:
d3

In [ ]:
d3.drop_duplicates(subset=['국어', '영어'])

## 시계열 데이터
- 다른 자료형을 시계열 객체로 변환
- to_datetime(): 문자열을 timestamp로 변환

In [ ]:
data = [['1990-03-02', 90], ['1991-08-08', 95], ['1990-11-22',90], ['1991-01-05', 88]]
names=['철수','영이','길동','미영']
column=['생년월일','점수']
d1 = pd.DataFrame(data, index=names, columns=column)
d1

          생년월일  점수
철수  1990-03-02  90
영이  1991-08-08  95
길동  1990-11-22  90
미영  1991-01-05  88

In [ ]:
d1.info()

In [ ]:
d1['생년월일'] = pd.to_datetime(d1['생년월일'])
d1

In [ ]:
d1.info()

- 시계열 데이터 활용
  - 날짜 데이터 분리: 연-월-일 정보에서 연,월,일 추출: dt.year, dt.month, dt.day를 사용

In [ ]:
d1['년'] = d1['생년월일'].dt.year
d1['월'] = d1['생년월일'].dt.month
d1['일'] = d1['생년월일'].dt.day
d1

         생년월일  점수     년   월   일
철수 1990-03-02  90  1990   3   2
영이 1991-08-08  95  1991   8   8
길동 1990-11-22  90  1990  11  22
미영 1991-01-05  88  1991   1   5

  - 연-월-일 정보에서 연-월 등 추출: dt.to_period()를 사용

In [ ]:
d1['년월'] = d1['생년월일'].dt.to_period(freq='M')
d1

         생년월일  점수     년   월   일       년월
철수 1990-03-02  90  1990   3   2  1990-03
영이 1991-08-08  95  1991   8   8  1991-08
길동 1990-11-22  90  1990  11  22  1990-11
미영 1991-01-05  88  1991   1   5  1991-01

- 날짜 인덱스 활용

In [ ]:
d2 = d1.set_index('생년월일')
d2

            점수     년   월   일       년월
생년월일
1990-03-02  90  1990   3   2  1990-03
1991-08-08  95  1991   8   8  1991-08
1990-11-22  90  1990  11  22  1990-11
1991-01-05  88  1991   1   5  1991-01

In [ ]:
d2['날짜_차이'] = today-d2.index
d2

## melt()를 이용한 데이터 정리
- 넓은 데이터: 데이터의 열 이름이 어떤 값을 의미하면 열의 폭이 넓은 경우가 많음
- melt()메서드는 지정한 열의 데이터를 모두 행으로 정리해준다.
  - id_vars: 위치를 그대로 유지할 열의 이름을 지정
  - value_vars: 행으로 위치를 변경할 열의 이름을 지정
  - var_name: value_vars로 위치를 변경한 열의 이름을 지정
  - value_name: var_name으로 위치를 변경한 열의 데이터를 저장한 열의 이름을 지정

In [ ]:
a = ['religion', '<$10k', '$10-20k', '$20-30k', '$30-40k', '$40-50k', '$50-75k', \
'$75-100k','$100-150k', '>150k', "Don't know/refused"]

data =[['Agnostic', 27, 34, 60, 81, 76, 137, 122, 109, 84, 96],\
       ['Atheist', 12, 27, 37, 52, 35, 70, 73, 59, 74, 76], \
       ['Buddhist', 27, 21, 30, 34, 33, 58, 62, 39, 53, 54], \
       ['Catholic', 418, 617, 732, 670, 638, 1116, 949, 792, 633, 1489], \
       ["Don't know/refused", 15, 14, 15, 11, 10, 35, 21, 17, 18, 116]]
df=pd.DataFrame(data, columns=a)
df

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don't know/refused,15,14,15,11,10,35,21,17,18,116

- 1개의 열만 고정하고 나머지 열을 행으로 바꾸기

In [ ]:
pew_long = pd.melt(df, id_vars='religion', var_name='income', value_name='count')
pew_long

## 피벗 테이블을 이용한 데이터 정리
- 피벗 테이블: 대화형 테이블의 일종으로, 데이터의 나열 형태에 따라서 집계나 카운트 등의 계산을 하는 기능
- .pivot_table(df, index=인덱스리스트, values=값리스트)

- https://raw.githubusercontent.com/HaesunByun/common/main/data/salesfunnel.xlsx

In [ ]:
df = pd.read_excel('https://raw.githubusercontent.com/HaesunByun/common/main/data/salesfunnel.xlsx')
df

- 특별히 지정하지 않으면 Name을 기준으로 숫자형 데이터 컬럼들이 남게 됨

In [ ]:
pd.pivot_table(df, index=['Name'])

- value를 pivot_table로 합친 경우 평균치가 기본이 됨

In [ ]:
pd.pivot_table(df, index=['Manager', 'Rep'], values=['Price'])

- value의 값을 합산으로 하고 싶을 때 aggfunc옵션에 sum함수의 이름을 쓴다.

In [ ]:
pd.pivot_table(df, index=['Manager', 'Rep'], values=['Price'], aggfunc=sum)